name: auth
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:

  # Firebase Authentication
  # 
  firebase_auth: ^4.6.0
  google_sign_in: ^6.1.0
  sign_in_with_apple:
  firebase_core: ^2.12.0
  # 
  # statemanagement
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  # 
  # error handal
  dartz:
  # 
  # utily

  # 
  flutter:
    sdk: flutter
  
  meta: ^1.8.0
  

dev_dependencies:
  firebase_auth_platform_interface: ^6.15.0
  firebase_core_platform_interface: ^4.8.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.4
