// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTwfmZ8g_LCyuzTG9hWQXVnV6DQlexczo',
    appId: '1:122382311574:web:cd1b1863112c364a83e2b7',
    messagingSenderId: '122382311574',
    projectId: 'fir-login-with-bloc-fba70',
    authDomain: 'fir-login-with-bloc-fba70.firebaseapp.com',
    storageBucket: 'fir-login-with-bloc-fba70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvozeJwaqHvBXB0DhGHRr7Ek07tkJPqtM',
    appId: '1:122382311574:android:fcfb73012e387ba183e2b7',
    messagingSenderId: '122382311574',
    projectId: 'fir-login-with-bloc-fba70',
    storageBucket: 'fir-login-with-bloc-fba70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5jq4I_S3g9TQlY7FQ3qwycYz4EJm_iwo',
    appId: '1:122382311574:ios:3c8189ff1299951b83e2b7',
    messagingSenderId: '122382311574',
    projectId: 'fir-login-with-bloc-fba70',
    storageBucket: 'fir-login-with-bloc-fba70.appspot.com',
    iosClientId: '122382311574-7veh2oig2dr4ejf0mufo11d03i9q6ocb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5jq4I_S3g9TQlY7FQ3qwycYz4EJm_iwo',
    appId: '1:122382311574:ios:e4b7ee7faea262d883e2b7',
    messagingSenderId: '122382311574',
    projectId: 'fir-login-with-bloc-fba70',
    storageBucket: 'fir-login-with-bloc-fba70.appspot.com',
    iosClientId: '122382311574-tf4jb31ggbb4ip8njp2hp00065i2u6lk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin.RunnerTests',
  );
}
